# Generated by Django 5.2.4 on 2025-11-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [
                    ("can_view_all_clients", "Может просматривать всех клиентов"),
                    ("can_block_client", "Может блокировать клиентов"),
                ],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
    ]
