# Generated by Django 5.2.4 on 2025-07-23 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attempts', '0002_initial'),
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.mailing', verbose_name='Рассылка'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['status'], name='attempts_at_status_3196f6_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['mailing'], name='attempts_at_mailing_8fbb3b_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['attempt_time'], name='attempts_at_attempt_18675a_idx'),
        ),
    ]
