# Generated by Django 5.2.4 on 2025-07-23 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailings', '0001_initial'),
        ('my_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_messages.message'),
        ),
    ]
