# Generated by Django 5.2.4 on 2025-11-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_mailing_first_sent_alter_mailing_clients_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["-start_time"],
                "permissions": [
                    ("can_view_all_mailings", "Может просматривать все рассылки"),
                    ("can_disable_mailing", "Может отключать рассылки"),
                    ("can_block_mailing", "Может блокировать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
