# Generated by Django 5.2.4 on 2025-11-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_messages", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [
                    ("can_view_all_messages", "Может просматривать все сообщения"),
                    ("can_block_message", "Может блокировать сообщения"),
                ],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
